spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:java-advanced-db
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

service:
  aluno:
    concat-id-to-aluno: enabled
